spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://db:3306/backend
    username: root
    password: root!
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: 'true'
